# Enable a "Sponsor" button on the repo. Uncomment and fill in what applies.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# github: [rizwan2004cs]
# ko_fi: your-handle
# buy_me_a_coffee: your-handle
# custom: ["https://finboom-cyan.vercel.app"]
