type TopicEntry = {
  title: string
  prePosted: boolean
}

const RAW_TOPICS_FROM_PDF = [
  "What Is True Wealth? Balancing Investing, Saving, and Enjoying Life at Every Age",
  "How Compounding Turns Small SIPs Into Crores Over Time",
  "~~The Psychology of Money: Why Most People Stay Broke Despite Good Income~~",
  "The Difference Between Being Rich and Being Financially Free",
  "Asset Allocation Explained for Indians in Their 20s, 30s, and 40s",
  "How to Build Wealth Even With a Small Salary in India",
  "The 1 Crore Roadmap: How Long It Really Takes With SIPs",
  "Why Most Indians Underestimate Inflation and Overestimate Savings",
  "The Power of Starting Early: A 5-Year Delay Can Cost You Lakhs",
  "Financial Habits That Quietly Make People Wealthy Over Time",
  "Why Your First 10 Lakhs Is the Hardest Milestone",
  "How to Build Multiple Income Sources Without Quitting Your Job",
  "Why Cash Flow Matters More Than Salary for Long-Term Wealth",
  "Understanding Net Worth: The Real Scorecard of Your Financial Life",
  "Lifestyle Inflation: The Silent Killer of Wealth Creation",
  "Fundamental Analysis: A Beginner's Guide to Reading Stocks Like a Pro",
  "Technical Analysis for Beginners: Understanding Charts Without Confusion",
  "Swing Trading vs Long-Term Investing: Which Fits Your Personality?",
  "How to Read Candlestick Patterns Like a Trader",
  "Understanding Support and Resistance With Real Examples",
  "Risk Management in Trading: Why Survival Matters More Than Profits",
  "How Retail Traders Lose Money in F&O and How to Avoid It",
  "The Truth About Intraday Trading: Is It Worth the Risk?",
  "Positional Trading vs SIP Investing: Which Builds Better Wealth?",
  "How to Analyze a Company Before Buying Its Stock",
  "P/E Ratio, ROE, and Debt Explained Like You're 15",
  "What Makes a Stock Expensive or Cheap?",
  "Bull Markets vs Bear Markets Explained Simply",
  "Sector Rotation: How Smart Investors Shift Money During Market Cycles",
  "How FIIs and DIIs Move the Indian Stock Market",
  "The AI Boom in Markets: Lessons From Previous Investment Hypes",
  "Why Long-Term Investors Usually Beat Most Traders",
  "Momentum Investing Explained With Indian Stock Examples",
  "Growth Stocks vs Value Stocks: Which One Wins Long-Term?",
  "How to Create a Long-Term Portfolio That Can Survive Market Crashes",
  "Why Emotions Destroy More Portfolios Than Bad Stocks",
  "Fear and Greed in the Stock Market Explained Visually",
  "Revenge Trading: The Fastest Way to Blow Up Your Capital",
  "The Hidden Psychology Behind Market Crashes and Rallies",
  "Why Beginners Overtrade and Professionals Wait",
  "How Social Media Influences Retail Investors",
  "FOMO Investing: Why Chasing Hype Usually Ends Badly",
  "Why Discipline Matters More Than Strategy in Trading",
  "The Truth About Quick Money in the Stock Market",
  "How Market Cycles Repeat Again and Again",
  "Emergency Funds Explained: How Much Money Should You Really Keep?",
  "Where Should Indians Keep Their Emergency Fund?",
  "Emergency Fund vs Investments: Why Both Matter",
  "How to Build a 6-Month Emergency Fund Without Feeling Burdened",
  "What Happens Financially If You Lose Your Job Tomorrow?",
  "Financial Planning for Medical Emergencies in India",
  "Why One Hospital Bill Can Destroy Years of Savings",
  "Creating a Financial Backup Plan for Your Family",
  "The Importance of Liquidity During Economic Crises",
  "Financial Lessons Indians Learned From COVID-19",
  "Health Insurance Explained for Young Indians",
  "Term Insurance vs Traditional Insurance Plans: Which Is Better?",
  "Why Insurance Is Not an Investment",
  "How Much Health Insurance Cover Do You Actually Need?",
  "Understanding Family Floater Health Insurance",
  "Why Young Professionals Ignore Insurance Until It's Too Late",
  "ULIPs Explained: Investment or Insurance?",
  "Common Insurance Mistakes Indian Families Make",
  "How to Financially Protect Your Parents and Dependents",
  "Emergency Medical Costs in India and How Insurance Helps",
  "Best Tax Saving Investments Under Section 80C",
  "ELSS vs PPF vs FD: Which Saves More Tax and Builds More Wealth?",
  "How Salaried Employees Can Legally Save More Tax",
  "Old Tax Regime vs New Tax Regime Explained Simply",
  "Tax Planning Mistakes That Cost Indians Thousands Every Year",
  "How HRA, NPS, and EPF Help Reduce Taxes",
  "Tax Harvesting Explained for Mutual Fund Investors",
  "Capital Gains Tax on Stocks and Mutual Funds Simplified",
  "Smart Tax Planning for Freelancers and Self-Employed Indians",
  "How Wealthy People Use Investments to Reduce Tax Burden",
  "How to Build Wealth for the Next Generation",
  "Financial Planning for Your Child's Education",
  "Should Parents Invest in Gold, Stocks, or Property for Children?",
  "Creating a Family Financial Plan That Lasts Decades",
  "Why Most Families Lose Wealth by the Third Generation",
  "Teaching Kids About Money in the Digital Age",
  "How to Leave Financial Security for Your Family",
  "Estate Planning and Nomination Basics Every Indian Should Know",
  "Building Passive Income That Supports Future Generations",
  "The Importance of Financial Literacy in Families",
  "Buying vs Renting: Which Makes More Financial Sense in India?",
  "Should You Buy a House Early or Invest First?",
  "Home Loan vs Investing: Where Should Your Money Go?",
  "Renting in Metro Cities vs Buying in Tier-2 Cities",
  "Real Estate vs Mutual Funds: Which Builds More Wealth?",
  "The Hidden Costs of Buying a House Nobody Talks About",
  "Is Real Estate Still a Good Investment in India?",
  "Should You Buy a Car or Invest the Money Instead?",
  "EMI Lifestyle: Convenience or Financial Trap?",
  "Minimalism and Wealth: Why Owning Less Sometimes Makes You Richer",
  "Business vs Job: Which Builds More Wealth Long-Term?",
  "Why High Salary Does Not Always Mean Financial Freedom",
  "How Side Hustles Can Accelerate Wealth Creation",
  "The Financial Reality of Startups Most People Ignore",
  "Should Young Indians Take Career Risks Early?",
  "How to Increase Income Faster Than Inflation",
  "Skills That Will Make Money in the AI Era",
  "Corporate Life vs Entrepreneurship: Financial Pros and Cons",
  "Why Income Growth Matters More Than Cutting Small Expenses",
  "Building Financial Stability as a Freelancer",
  "FIRE Movement Explained for Indians",
  "How Much Money Do You Really Need to Retire Comfortably?",
  "Early Retirement in India: Dream or Reality?",
  "The 4% Rule Explained for Indian Investors",
  "Retirement Planning in Your 20s vs 40s",
  "Passive Income Ideas for Financial Independence",
  "Why Retirement Is More About Cash Flow Than Corpus Size",
  "Best Investment Options for Retirement Planning in India",
  "Common Retirement Planning Mistakes Indians Make",
  "Financial Freedom vs Luxury Lifestyle: Understanding the Difference",
  "SIP vs Lump Sum Investing Explained Simply",
  "Mutual Funds for Beginners: Everything You Need to Know",
  "Index Funds vs Active Funds: Which Is Better?",
  "How Inflation Quietly Makes Everything Expensive",
  "Budgeting for Beginners Without Feeling Restricted",
  "The 50-30-20 Rule Explained for Indian Salaries",
  "Credit Cards: Smart Tool or Debt Trap?",
  "Understanding CIBIL Score and Why It Matters",
  "How Compound Interest Actually Works",
  "Money Habits Every College Student Should Learn Early",
]

export function normalizeTopic(value: string): string {
  return value
    .toLowerCase()
    .replace(/[`~]/g, "")
    .replace(/[^\w\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim()
}

export function getSeedTopics(): TopicEntry[] {
  return RAW_TOPICS_FROM_PDF.map((raw) => {
    const trimmed = raw.trim()
    const prePosted = /^~~.*~~$/.test(trimmed)
    const title = trimmed.replace(/^~~/, "").replace(/~~$/, "").trim()
    return { title, prePosted }
  })
}

