import { createClient } from "@supabase/supabase-js"
import webpush from "web-push"
import { sanityClient } from "@/lib/sanity"
import { generateBlogFromTopic, generateTopicFallbacks } from "@/lib/blog/ai-generation"
import { markdownToPortableText, slugify } from "@/lib/blog/markdown-to-portable-text"
import { isTooSimilar, normalizeTopic } from "@/lib/blog/topic-utils"
import { uploadHeroImageToSanity } from "@/lib/blog/sanity-image"
import { pickTargetCategory } from "@/lib/blog/category-balancer"
import { getKeywordIdeas, getCurrentSeasonContext } from "@/lib/blog/trends"
import {
  addFallbackTopicsToQueue,
  getNextPendingTopicFromQueue,
  getQueueHealth,
  listPendingQueueTopics,
  markQueueTopicPosted,
  seedTopicQueueIfNeeded,
  skipQueueTopic,
  syncQueueWithPublishedTitles,
} from "@/lib/blog/topic-queue"

// The cron fires once a day, but each post publishes ~30-60s after the
// trigger. A strict 24h guard would then see the previous post as "just
// under 24h old" on the next run and skip it, posting only every other day.
// A 12h window guarantees the daily run always posts while still blocking
// accidental double-posts (e.g. a retried cron or manual re-trigger).
const MIN_GAP_BETWEEN_AUTO_POSTS_MS = 12 * 60 * 60 * 1000

type ExistingPost = {
  title: string
  slug?: string
  category?: string
  publishedAt?: string
  autoGenerated?: boolean
}

type PushSubscriptionRow = {
  id: string
  user_id: string
  endpoint: string
  keys_p256dh: string
  keys_auth: string
}

type SelectedTopic = {
  title: string
  source: "db_queue" | "ai_fallback"
  queueId?: string
}

type NotificationResult = {
  usersNotified: number
  pushesSent: number
  skipped?: string
}

export type BlogAutomationRun =
  | { status: "skipped"; reason: string; latestTitle?: string; publishedAt?: string }
  | { status: "no_topic" }
  | {
      status: "published"
      topic: string
      topicSource: string
      title: string
      slug: string
      notification: NotificationResult
      queue: Awaited<ReturnType<typeof getQueueHealth>>
    }

function toUniqueSlug(title: string, existingSlugs: Set<string>) {
  const base = slugify(title) || `blog-${new Date().toISOString().slice(0, 10)}`
  if (!existingSlugs.has(base)) return base

  const dateSuffix = new Date().toISOString().slice(0, 10)
  const dated = `${base}-${dateSuffix}`
  if (!existingSlugs.has(dated)) return dated

  let counter = 2
  while (existingSlugs.has(`${dated}-${counter}`)) {
    counter += 1
  }
  return `${dated}-${counter}`
}

async function fetchExistingPosts(): Promise<ExistingPost[]> {
  return sanityClient.fetch(
    `*[_type == "post"] | order(publishedAt desc) {
      title,
      "slug": slug.current,
      category,
      publishedAt,
      autoGenerated
    }`
  )
}

async function findAiFallbackTopic(existingTitles: string[]): Promise<SelectedTopic | null> {
  const postedSet = new Set(existingTitles.map((title) => normalizeTopic(title)))

  let aiCandidates: string[] = []
  try {
    aiCandidates = await generateTopicFallbacks(existingTitles)
  } catch {
    aiCandidates = []
  }
  for (const topic of aiCandidates) {
    if (!postedSet.has(normalizeTopic(topic)) && !isTooSimilar(topic, existingTitles)) {
      return { title: topic, source: "ai_fallback" }
    }
  }

  return null
}

async function selectTopic(existingTitles: string[]): Promise<SelectedTopic | null> {
  await seedTopicQueueIfNeeded()
  await syncQueueWithPublishedTitles(existingTitles)

  // Walk the queue head, auto-skipping topics too similar to something
  // already published (prevents near-duplicate posts).
  const pendingTopics = await listPendingQueueTopics(10)
  for (const pending of pendingTopics) {
    if (isTooSimilar(pending.title, existingTitles)) {
      await skipQueueTopic(pending.id)
      continue
    }
    return { title: pending.title, source: "db_queue", queueId: pending.id }
  }

  // Fall back to the single-topic fetch in case the queue has more
  // pending rows beyond the similarity-checked window.
  const queuedTopic = await getNextPendingTopicFromQueue()
  if (queuedTopic && !isTooSimilar(queuedTopic.title, existingTitles)) {
    return { title: queuedTopic.title, source: "db_queue", queueId: queuedTopic.id }
  }

  let aiCandidates: string[] = []
  try {
    aiCandidates = await generateTopicFallbacks(existingTitles)
  } catch {
    aiCandidates = []
  }
  const postedSet = new Set(existingTitles.map((title) => normalizeTopic(title)))
  const queueableCandidates = aiCandidates.filter(
    (topic) => !postedSet.has(normalizeTopic(topic)) && !isTooSimilar(topic, existingTitles)
  )
  if (queueableCandidates.length > 0) {
    await addFallbackTopicsToQueue(queueableCandidates)
    const fallbackFromQueue = await getNextPendingTopicFromQueue()
    if (fallbackFromQueue) {
      return { title: fallbackFromQueue.title, source: "db_queue", queueId: fallbackFromQueue.id }
    }
  }

  return findAiFallbackTopic(existingTitles)
}

async function publishToSanity(post: Record<string, unknown>) {
  const token = process.env.SANITY_EDITOR_TOKEN
  const projectId = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID
  const dataset = process.env.NEXT_PUBLIC_SANITY_DATASET
  if (!token || !projectId || !dataset) {
    throw new Error("Sanity environment variables are not configured.")
  }

  const response = await fetch(
    `https://${projectId}.api.sanity.io/v2024-01-01/data/mutate/${dataset}`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({ mutations: [{ create: post }] }),
    }
  )

  const data = await response.json()
  if (!response.ok) {
    throw new Error(data.error?.description || "Failed to publish post to Sanity.")
  }

  return data
}

function configureWebPush() {
  const publicKey = process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY
  const privateKey = process.env.VAPID_PRIVATE_KEY
  if (!publicKey || !privateKey) {
    return false
  }

  webpush.setVapidDetails("mailto:rizwan22cse@gmail.com", publicKey, privateKey)
  return true
}

async function broadcastBlogNotification(
  title: string,
  excerpt: string,
  slug: string
): Promise<NotificationResult> {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
  const supabaseServiceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY
  if (!supabaseUrl || !supabaseServiceRoleKey) {
    return { usersNotified: 0, pushesSent: 0, skipped: "Missing Supabase service role key." }
  }

  const supabase = createClient(supabaseUrl, supabaseServiceRoleKey)

  if (!configureWebPush()) {
    return {
      usersNotified: 0,
      pushesSent: 0,
      skipped: "Missing VAPID keys.",
    }
  }

  const { data: subscriptions } = await supabase
    .from("push_subscriptions")
    .select("*")

  if (!subscriptions?.length) {
    return { usersNotified: 0, pushesSent: 0 }
  }

  const uniqueUserIds = [...new Set(subscriptions.map((subscription) => subscription.user_id).filter(Boolean))]

  let pushesSent = 0
  for (const subscription of subscriptions as PushSubscriptionRow[]) {
    const payload = JSON.stringify({
      title: `New blog: ${title}`,
      body: excerpt || "A new post has been published on FinBoom.",
      icon: "/icons/icon-192.svg",
      badge: "/icons/icon-192.svg",
      data: { url: `/blog/${slug}` },
    })

    try {
      await webpush.sendNotification(
        {
          endpoint: subscription.endpoint,
          keys: {
            p256dh: subscription.keys_p256dh,
            auth: subscription.keys_auth,
          },
        },
        payload
      )
      pushesSent += 1
    } catch (err: unknown) {
      if (
        err &&
        typeof err === "object" &&
        "statusCode" in err &&
        (err as { statusCode?: number }).statusCode === 410
      ) {
        await supabase.from("push_subscriptions").delete().eq("id", subscription.id)
      }
    }
  }

  return { usersNotified: uniqueUserIds.length, pushesSent }
}

// Runs the full pipeline: topic selection -> generation -> publish -> notify.
// `force` skips the once-per-24h guard (used by the admin manual trigger).
export async function runBlogAutomation({ force = false }: { force?: boolean } = {}): Promise<BlogAutomationRun> {
  const posts = await fetchExistingPosts()
  const now = Date.now()

  if (!force) {
    const latestAutoPost = posts.find((post) => post.autoGenerated && post.publishedAt)
    if (latestAutoPost?.publishedAt) {
      const ageMs = now - new Date(latestAutoPost.publishedAt).getTime()
      if (ageMs < MIN_GAP_BETWEEN_AUTO_POSTS_MS) {
        return {
          status: "skipped",
          reason: "Auto blog already published within the last 12 hours.",
          latestTitle: latestAutoPost.title,
          publishedAt: latestAutoPost.publishedAt,
        }
      }
    }
  }

  const existingTitles = posts.map((post) => post.title).filter(Boolean)
  const selectedTopic = await selectTopic(existingTitles)
  if (!selectedTopic) {
    return { status: "no_topic" }
  }

  // Steer the publishing mix toward under-represented categories and feed the
  // writer trending + seasonal keywords (best-effort; never blocks the post).
  const recentCategories = posts.map((post) => post.category).filter((c): c is string => Boolean(c))
  const targetCategory = pickTargetCategory(recentCategories)
  let keywords: string[] = []
  let seasonContext: string | undefined
  try {
    keywords = await getKeywordIdeas(targetCategory)
    seasonContext = getCurrentSeasonContext()
  } catch {
    // Trends are optional - generation continues without them.
  }

  const generated = await generateBlogFromTopic(selectedTopic.title, {
    targetCategory,
    keywords,
    seasonContext,
  })
  const body = markdownToPortableText(generated.content)

  const existingSlugs = new Set(posts.map((post) => post.slug).filter(Boolean) as string[])
  const slug = toUniqueSlug(generated.title, existingSlugs)

  const mainImage = generated.heroImageUrl
    ? await uploadHeroImageToSanity(generated.heroImageUrl)
    : null

  const post = {
    _type: "post",
    title: generated.title,
    slug: { _type: "slug", current: slug },
    category: generated.category,
    excerpt: generated.excerpt,
    ...(generated.metaTitle && { metaTitle: generated.metaTitle }),
    ...(generated.metaDescription && { metaDescription: generated.metaDescription }),
    ...(generated.keywords.length > 0 && { keywords: generated.keywords }),
    publishedAt: new Date().toISOString(),
    body,
    autoGenerated: true,
    sourceTopic: selectedTopic.title,
    topicSource: selectedTopic.source,
    ...(mainImage && { mainImage }),
  }

  await publishToSanity(post)
  if (selectedTopic.queueId) {
    await markQueueTopicPosted({
      id: selectedTopic.queueId,
      publishedTitle: generated.title,
      publishedSlug: slug,
    })
  }
  const notifyResult = await broadcastBlogNotification(generated.title, generated.excerpt, slug)
  const queueHealth = await getQueueHealth()

  return {
    status: "published",
    topic: selectedTopic.title,
    topicSource: selectedTopic.source,
    title: generated.title,
    slug,
    notification: notifyResult,
    queue: queueHealth,
  }
}
